spring:
  application:
    name: vars-management-service
    version: @project.version@
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
feign:
  client:
    config:
      default:
        readTimeout: 1800000
server:
  port: 8080
  servlet:
    context-path: /vmanagement
noodev:
  logs:
    level: INFO # Optional. Default is INFO
    kpi-logs:
      application-code: MY-APPLICATION # Optional. Default ApplicationCode value
      service-code: ${spring.application.name} # Optional. Default ServiceCode value
      allow-url-patterns: /**